name: tirec_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  firebase_core: 1.8.0
  firebase_auth: 3.1.4
  cloud_firestore: 2.5.4

  flutter: 
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  firebase_storage: ^10.0.6
  image_picker: ^0.8.4+4
  path: ^1.8.0
  io: ^1.0.3
  flutter_svg: ^1.0.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

